---
version: "3.7"

services:

  modem1:
    image: clintmod/kuwfi-monitor:latest
    environment:
      - HOST=192.168.100.1
    deploy:
      restart_policy:
          condition: any
          delay: 5s

  modem2:
    image: clintmod/kuwfi-monitor:latest
    environment:
      - HOST=192.168.102.1
    deploy:
      restart_policy:
          condition: any
          delay: 5s
